[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
broadcast = "broadcast"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@prb/math/=lib/prb-math/src/"
]
bytecode_hash = "none"
cbor_metadata = false
revert_strings = "strip"

[profile.default.fuzz]
runs = 1000
max_test_rejects = 100000

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false

[rpc_endpoints]
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
bsc_mainnet = "${BSC_MAINNET_RPC_URL}"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
bsc_mainnet = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api", chain = "bsc" }


